<a href="https://colab.research.google.com/github/Pavangitalg/pavanlearning_python/blob/main/Day22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Learning numpy in Python**

In [6]:
import numpy as np # numeric python
arr=np.array([1,2,3,4,5])
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1 + arr2


array([5, 7, 9])

In [45]:
arr= np.array([1,2,3,4,5,6,7,8])
arr.shape
# for i in arr:
#   arr4=np.array([-i])
#   i-=1
# print(arr4)
print(arr[-1:-9:-1])
arr.shape
arr.reshape(2,4)
arr+1   ### broadcasting is a very good feature in the numpy , so in this case 1 will be added to each element of the orignial array
# Broadcasting is used in the matrix operations kind of dot product


[8 7 6 5 4 3 2 1]


array([2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
m1= np.array([[1,2],[3,4]])   ##a1*c1+a2*d1  ### a1*c2+a2*d2
m2= np.array([[7,8],[9,10]])  ##b1*7+a2*d1   ### b1*c2+b2*d2
np.dot(m1,m2)

array([[25, 28],
       [57, 64]])

In [48]:
np.mean(arr)

4.5

In [50]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.std(arr)

2.29128784747792

In [53]:
np.random.rand(10)

array([0.86880062, 0.48398165, 0.49463191, 0.01386375, 0.93956717,
       0.36831358, 0.22277674, 0.95989299, 0.48446411, 0.28841561])

In [55]:
arr= [1,2,3, np.nan,4,5,6]
arr

[1, 2, 3, nan, 4, 5, 6]

In [56]:
np.isnan(arr)

array([False, False, False,  True, False, False, False])

#### **list Vs np.array compraison**

In [10]:
import time
ls1=list(range(10000000))
start=time.time()
sum(ls1)
end=time.time()
print(end-start)

0.07883739471435547


In [11]:
import time
import numpy as np
ls1=np.array(ls1)
start=time.time()
np.sum(ls1)
end=time.time()
print(end-start)

0.010515451431274414
